modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/environmental/issues"
license = "https://github.com/team-abnormals/environmental/blob/main/LICENSE.txt"

[[mods]]
    modId = "environmental"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "environmental:wanderer_boots"
    configBackground = "environmental:textures/block/willow_planks.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, Farcr, hatsondogs, Jackson, Ocelot, Echolite, five"
    displayURL = "https://www.teamabnormals.com/mods/environmental"
    displayName = "Environmental"
    description = '''
    Expanding the environment. New wood, new blocks, new friends.
    '''

[[dependencies.environmental]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.19.3)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.environmental]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.environmental]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.2.0,)"
    ordering = "AFTER"
    side = "BOTH"